### ISSUE TITLE
Previous / Old State in WhenChangedTo

### ISSUE THREAD

**Issue by woellij** [builttoroam/BuildIt#5]
Hi there.

I've been using your States library for a recent Xamarin.Forms project. New requirements emerged and inone control i need to make different animations depending on the previous state ('navigation' translation vs fade).

Is there a way to get the previous / old state somehow? I thought about using DefineStateWithData and pass the old state in as data, but i probably misinterpreted the role 'data' plays, because it is required to implement INotifyPropertyChanged.

Cheers,
Johannes

**Comment by nickrandolph** [comment]
@woellij you can use the WhenChangingFrom or the WhenAboutToChange methods to record the state that you're leaving.

**Comment by woellij** [comment]
thanks! did it and worked. 

i've just seen that you also provide xamarin forms XAML visual state manager. will have to try that next :) 

Thanks for the great library! Keep it up :)

**Comment by nickrandolph** [comment]
Just posted about animations in the Forms library - https://nicksnettravels.builttoroam.com/post/2017/06/25/Visual-State-Transitions-in-Xamarin-Forms-with-Animations.aspx

**Comment by woellij** [comment]
Thanks for the heads-up! I'll try that with the next control.
