### ISSUE TITLE
BuildIt.Forms package profile version

### ISSUE THREAD

**Issue by sethom** [builttoroam/BuildIt#50]
What profile version does this require? I successfully installed BuildIt.General and BuildIt.States into an XF project targeting  PCL 4.5 - Profile259 but getting this with BuildIt.Forms in VS for Mac:

"Could not install package 'BuildIt.Forms 1.1.0.103'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

What do I need to target?

**Comment by nickrandolph** [comment]
General and States are both .net standard 1.0 libraries, where as Forms is a .net standard 1.4 at the moment. My recommendation would be to migrate your library across to being a .net standard library which should make working with all modern nuget libraries much easier going forward. I've got a couple of posts that talk about using .net standard (https://nicksnettravels.builttoroam.com/post/2017/09/13/Getting-Started-Xamarin-Forms-with-NET-Standard-20.aspx), so hope they help

**Comment by sethom** [comment]
Thanks, I've been working on this today as a matter of fact. I suspected this was the issue.
