### ISSUE TITLE
PCL Version

### ISSUE THREAD

**Issue by renyg25** [builttoroam/BuildIt#52]
Hi,

It is very nice to use the VisualState in Xamarin Forms. Do you have the version to support PCL ?

Thanks.

**Comment by nickrandolph** [comment]
You can use the States library by itself. Add reference to Buildit.states from nuget. It doesn’t define states in xaml (that’s only supported in XF) but does allow you to manage states.

What’s the scenario you’re trying to achieve?

**Comment by renyg25** [comment]
That's cool. I just want to use the VisualStateManager like UWP.

I need to add different VisualStates for the Controls.

**Comment by nickrandolph** [comment]
In that

**Comment by renyg25** [comment]
Is it possible to use it in xaml for XF(PCL) like below?

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
              xmlns:vsm="clr-namespace:BuildIt.Forms.Core;assembly=BuildIt.Forms.Core"
              xmlns:local="clr-namespace:FormsWithStates"
              x:Class="FormsWithStates.MainPage">
     <vsm:VisualStateManager.VisualStateGroups>
         <x:Array Type="{x:Type vsm:VisualStateGroup}">
             <vsm:VisualStateGroup Name="SampleStates">
                <vsm:VisualState Name="Show" />
                 <vsm:VisualState Name="Hide">
                     <vsm:VisualState.Setters>
                         <vsm:Setter Value="false"
                                     Target="WelcomeText.IsVisible" />
                     </vsm:VisualState.Setters>
                 </vsm:VisualState>
             </vsm:VisualStateGroup>
         </x:Array>
     </vsm:VisualStateManager.VisualStateGroups>
     <StackLayout VerticalOptions="Center"
                  HorizontalOptions="Center">
         <Label x:Name="WelcomeText"
                Text="Welcome to Xamarin Forms!" />
         <StackLayout Orientation="Horizontal">
             <Button Text="Show"
                     Clicked="ShowClicked" />
             <Button Text="Hide"
                     Clicked="HideClicked" />
         </StackLayout>
     </StackLayout>
</ContentPage>

**Comment by nickrandolph** [comment]
Sorry accidentally closed this instead of replying.

You should be able to add the Buildit.forms nuget to your PCL. It’s a net standard library but should work with PCL libraries. If not I would recommend switching your library to net standard ASAP regardless

**Comment by renyg25** [comment]
I'm not able to use the BuildIt.Forms to my PCL. It's only support net standard. I'll try to switch later. Thanks very much.

**Comment by nickrandolph** [comment]
hold off - I'm just pushing out an update (as beta) which should add PCL support

**Comment by nickrandolph** [comment]
Give https://www.nuget.org/packages/BuildIt.Forms/1.1.0.111-beta a try. I've downgraded to netstandard 1.0 (there was no reason for it to be netstandard 1.4) so you should be able to add it to a PCL, assuming you have picked on of the compatible profile levels (eg Profile259)

**Comment by renyg25** [comment]
Let me try it, great thanks.

**Comment by renyg25** [comment]
Now it's working very good on PCL and it's very nice to have this function on Xamarin Forms development. Thanks very much.

BTW, if anyone else sees this post. The visual state manager code is changed, not the one I post above. 

<vsm:VisualStateManager.VisualStateGroups>
     <vsm:VisualStateGroups>
         <vsm:VisualStateGroup Name="LoadingStates">
             <vsm:VisualState Name="Loading">
                 <vsm:VisualState.Setters>
                     <vsm:Setter Element="{x:Reference LoadingIndicator}"
                                 Property="IsVisible"
                                 Value="true" />
                 </vsm:VisualState.Setters>
             </vsm:VisualState>
             <vsm:VisualState Name="Loaded" />
         </vsm:VisualStateGroup>
     </vsm:VisualStateGroups>
</vsm:VisualStateManager.VisualStateGroups>

Ref : https://nicksnettravels.builttoroam.com/post/2017/10/15/Getting-Started-with-Visual-States-in-Xamarin-Forms-using-BuildItForms.aspx

**Comment by nickrandolph** [comment]
@renyg25 Thanks for the feedback - we'll look to push that version to stable shortly.

**Comment by nickrandolph** [comment]
@renyg25 FYI the stable version 1.1.0.111 is now available - https://www.nuget.org/packages/BuildIt.Forms/1.1.0.111
